# Site settings
title: Hong Kong Code Conf 2016 - Saturday 15th October @ Credit Suisse - 88/F ICC
email: matthewrudyjacobs@gmail.com
description: >
  Hong Kong Code Conf will be held on Saturday 15th October 2016.
  It's a programming conference aimed at all programmers in Hong Kong.
  We want to share our skills and opinions.
  We want to inspire each other with our passion.
  We want to build a closer, stronger community.

url: "http://hongkong.codeconf.io"

# Build settings
markdown: kramdown
sass:
  style: compressed

# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   profile: false
#   ignore:
#     envs: [local]
